### ISSUE TITLE
Azzio HW version sample set won't convert

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/OdfEdit#70]
Trying to convert https://piotrgrabowski.pl/azzio/ HW version with 2.18 and it gets stuck saying "Building GrandOrgue manuals..." and a spinning mouse pointer when over the OdfEdit window. Never worked in any earlier version that I've tried either.

Even if there's a GO version available for this sample set it might be worthwhile to investigate why the HW version won't convert.

**Comment by larspalo** [comment]
Information from the command line:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "./OdfEdit.py", line 13093, in file_open
    if self.odf_hw2go.GO_ODF_build_from_HW_ODF(file_name, GO_odf_file_name, self.progress_status_update,
  File "./OdfEdit.py", line 6106, in GO_ODF_build_from_HW_ODF
    self.GO_ODF_build_Manual_object(HW_keyboard_dic)
  File "./OdfEdit.py", line 7017, in GO_ODF_build_Manual_object
    self.GO_ODF_build_Manual_keyimage_by_switch(keys_switch_dic[midi_note_nb], keys_switch_dic[midi_note_nb + 1], GO_panel_element_dic, GO_key_nb, layout_id)
KeyError: 37
```

**Comment by eturpault** [comment]
Looks same issue as https://github.com/GrandOrgue/OdfEdit/issues/66
which is fixed for next release.

**Comment by eturpault** [comment]
This is fixed in OdfEdit v2.19

**Comment by larspalo** [comment]
> fixed in OdfEdit v2.19

No, unfortunately not. I still get a hang building manuals and this on the terminal:

```
/Sources/OdfEdit-2.19/src$ python3 ./OdfEdit.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "./OdfEdit.py", line 13115, in file_open
    if self.odf_hw2go.GO_ODF_build_from_HW_ODF(file_name, GO_odf_file_name, self.progress_status_update,
  File "./OdfEdit.py", line 6122, in GO_ODF_build_from_HW_ODF
    self.GO_ODF_build_Manual_object(HW_keyboard_dic)
  File "./OdfEdit.py", line 7033, in GO_ODF_build_Manual_object
    self.GO_ODF_build_Manual_keyimage_by_switch(keys_switch_dic[midi_note_nb], keys_switch_dic[midi_note_nb + 1], GO_panel_element_dic, GO_key_nb, layout_id)
KeyError: 37
```

**Comment by eturpault** [comment]
I am not able to reproduce this hang, with neither OdfEdit v2.19 nor v2.18, but I have observed an issue which is probably causing your hang.
In the HW ODF of this sample set, for the three keyboards the key with midi note 37 is using the image of the key with midi note 62 (and it is using the audio sample of the key with midi note 36, but this is not causing the hang).
I have made OdfEdit mode robust in the keys image conversion, could you please test the Linux binary below and say me if you are still observing this hang ?

[OdfEdit_keys_improvement.zip](https://github.com/user-attachments/files/19827214/OdfEdit_keys_improvement.zip)

**Comment by eturpault** [comment]
I have reproduced the issue with the HW ODF you have shared.
In your ODF, the keys with MIDI note 37 are not defined at all in the ODF, for all manuals.
In the ODF I have in my side (downloaded on April 20th 2025 on the Piotr's website), the keys 37 are defined but with a key ID which is higher than the ID of the last key of their manual, like if Piotr had realized that this key was missing and added it at a time after you downloaded this sample set.
I have added in OdfEdit for the next version the management of a missing key definition (which should never happen normally).
Thanks for the report, it was an interresting case.

Here is the demo HW ODF I have in my side : [Azzio.zip](https://github.com/user-attachments/files/19967316/Azzio.zip)

**Comment by larspalo** [comment]
@eturpault I can confirm that the conversion (kind of) works with the ODF that you have, while it doesn't with the one that I had downloaded (much earlier). Thanks for your effort investigating this!

The following obvious errors are still existing, even with your ODF conversion:

- MIDI key 037 out of the box plays the same pitch as 036 and is not adjusted with PitchTuning (all keys, all keyboards). There are very likely other ways in GO to have an old compass without the 037 key than what HW provides... I can expand on this if interest exist. But possibly there are already options to "correct" this in OdfEdit (that I've not yet tested).
- Bordone (manual II) has the 066 key playing the same pitch as 065 without PitchTuning adjustment.
- Flauto Conico (of manual II) has the 052 key playing the same pitch as 050 (not getting correctly adjusted with PitchTuning). The same is with 067 and 065 of the same stop/rank.
- The Sesquialtera of manual I should have its ranks (2 2/3 and 1 3/5) splittable, playing only 2 2/3 in one position and both in the second. This is currently not correctly modelled in the OdfEdit port to GO.
- Ripieno (manual I) has the044 key playing the same pitch as 046 with no PitchTuning adjustment provided.
- Ripieno (manual I) has the 062 key playing the same pitch as 064 with no PitchTuning adjustment provided.
- Ripieno (manual I) has the 073 key playing the same pitch as 075 with no PitchTuning adjustment provided.

**Comment by larspalo** [comment]
@eturpault While your development version works for Azzio it also sadly has regressions that cause a similar hang trying to convert St. Michel en Thierache. The 2.19 version handles St. Michel just fine though.

**Comment by eturpault** [comment]
I have detected this regression in the v2.20 some days ago with another sample set of Sonus Paradisi, it is already fixed. St. Michel en Thierache is converted without hang, I have checked.

About the keys playing a wrong pitch, I don't reproduce all what you have reported. With the sample set that I have recovered recently, when the Azzio HW ODF is converted to a GO ODF, OdfEdit detects that the MIDI note of each sample has to be retrieved from the sample files metadata, and there are actually PitchTuning attributes set in the GO ODF when needed. You should maybe download again the entire HW sample set from the Piotr's website.

About the Sesquialtera stop, indeed its behavior is not the good one with the generated GO ODF. The way Piotr has implemented the three states switch in the HW ODF cannot be converted similarly in a GO ODF according to me, it is too much complex, and the GO ODF syntax does not permit to have same controlling features and 3 states switch / images.
In the GO ODF edited by Piotr the controlling logic is different and simpler compared to the one used in the HW ODF, and OdfEdit cannot change a controlling logic.

**Comment by larspalo** [comment]
@eturpault Great that you already have fixed that!

It's quite possible that if I'd enabled the adjustments from metadata it would be fine. I just used the defaults for a quick test.

> OdfEdit cannot change a controlling logic.

Of course, that wouldn't make sense. Thanks for looking into it!

**Comment by eturpault** [comment]
I forgot to mention that in the case of Azzio (with the sample set I have downloaded recently) the PitchTuning attributes are set without having to enable in OdfEdit the option "correct pipes pitch from samples metadata". This is because the HW ODF has an attribute in each sample's section requiring to apply a pitch tuning using the MIDI note defined in the metadata of the sample file.
